// Augments the Wrangler-generated `CloudflareEnv` interface (cloudflare-env.d.ts,
// which is gitignored and regenerated by `npm run cf-typegen`). Declared here so
// secrets set via `wrangler secret put` are typed without hand-editing generated files.
interface CloudflareEnv {
  /** Resend API key - powers the /contact form. Set as a Cloudflare secret in prod. */
  RESEND_API_KEY?: string;
}
